apiVersion: v1
kind: ConfigMap
metadata:
 name: nginx-config
 namespace: nginx
data:
 index.html: |
   <html>
   <head><title>nginx appf</title></head>
   <body>
   <h1>Hello Commit Ravid </h1>
   </body>
   </html>